[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "next"

  [build.environment]
  NODE_VERSION = "18.18.0"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[env]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDKKayop62AaoC5DnYz5UuDpJIT3RBRX3M"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "cgsp-app.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "cgsp-app"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "your_project.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "your_sender_id"
  NEXT_PUBLIC_FIREBASE_APP_ID = "your_app_id"
  NEXT_PUBLIC_SUPABASE_URL = "https://wnkgiquiljtdxjyajsxg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indua2dpcXVpbGp0ZHhqeWFqc3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDA3NzQsImV4cCI6MjA2ODk3Njc3NH0.BnAskPNwV127xRgguN4DMJRHGINYbiqvrCi9-HetBAs"
